# SwiftLint configuration for PhotoReviewApp

included:
  - PhotoReviewApp

excluded:
  - PhotoReviewApp/Preview Content
  - PhotoReviewWidgets
  - PhotoReviewAppTests
  - PhotoReviewAppUITests

disabled_rules:
  - trailing_comma
  - todo
  - opening_brace

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - first_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
    - p

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 60

nesting:
  type_level: 3
  function_level: 3

large_tuple:
  warning: 4
  error: 5

reporter: xcode
